"""Markdown report emitter."""

from __future__ import annotations

import re

from consistency_check.stage import next_stage, stage_rank
from consistency_check.types import Finding, FindingStatus, Stage, Tier

_TIER_ORDER = (Tier.MUST, Tier.SHOULD, Tier.MAY)
# Evidence is a short single-line token by convention — a name, a filename, a
# marker. `test_evidence_contract` is what enforces that; this cap is only a
# backstop for a matcher that starts capturing a span of the audited repo's
# source, and it bounds the issue body rather than making such a matcher safe:
# it keeps the front of the span, which is the part worth not publishing. A body
# over the GitHub API's 65,536-character limit aborts that repo's filing, so no
# child issues get created for it; later repos still run.
_EVIDENCE_LIMIT = 500


_PRINTABLE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def _fence(text: str) -> str:
    """Wrap evidence in a backtick fence long enough to contain it.

    Evidence lands in a public issue body, where an unfenced identifier holding
    ``@name`` or ``#12`` posts as a live mention or a cross-reference to whoever
    happens to own that handle or number.

    Control characters are dropped rather than fenced. Sources are decoded with
    ``errors="replace"``, so a NUL in an audited repo's file survives into
    evidence, and ``subprocess`` rejects an argument containing one — which
    aborts the run with a ``ValueError`` the CLI does not catch, rather than
    the exit code 3 a filing failure is supposed to produce.
    """
    text = " ".join(_PRINTABLE.sub("", text).split()) or "(empty)"
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * (longest + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def _cap(text: str) -> str:
    return text if len(text) <= _EVIDENCE_LIMIT else text[:_EVIDENCE_LIMIT] + "… (truncated)"


def _evidence(finding: Finding) -> str:
    return _fence(_cap(finding.evidence))


def render_umbrella(
    repo_name: str, findings: list[Finding], *, declared_stage: Stage | None = None
) -> str:
    """Render a per-repo umbrella issue body summarizing all findings."""
    summary = _summary_table(findings)
    failures = [f for f in findings if f.status == FindingStatus.FAIL]
    must_fails = [f for f in failures if f.tier == Tier.MUST]
    should_fails = [f for f in failures if f.tier == Tier.SHOULD]
    may_fails = [f for f in failures if f.tier == Tier.MAY]
    errors = [f for f in findings if f.status == FindingStatus.ERROR]

    lines: list[str] = [
        f"# Consistency audit: `{repo_name}`",
        "",
        "Generated by `consistency-check`. "
        "Authoritative standards: `consistency-check/docs/standards/`.",
        "",
        "## Summary",
        "",
        summary,
        "",
    ]

    lines += _stage_section(findings, declared_stage)

    if must_fails or should_fails:
        lines += ["## Required fixes (MUST / SHOULD)", ""]
        if must_fails:
            lines += [f"### MUST ({len(must_fails)})", ""]
            lines.extend(
                f"- **{f.rule_id}** — {_evidence(f)} → see child issue." for f in must_fails
            )
            lines.append("")
        if should_fails:
            lines += [f"### SHOULD ({len(should_fails)})", ""]
            lines.extend(
                f"- **{f.rule_id}** — {_evidence(f)} → see child issue." for f in should_fails
            )
            lines.append("")

    if may_fails:
        lines += [f"## Suggestions (MAY) — {len(may_fails)}", ""]
        lines.extend(f"- **{f.rule_id}** — {_evidence(f)}" for f in may_fails)
        lines.append("")

    if errors:
        lines += [f"## Audit errors ({len(errors)})", ""]
        lines.extend(f"- **{f.rule_id}** — {_fence(_cap(f.evidence or 'unknown'))}" for f in errors)
        lines += [
            "",
            "Detail is on the audit run's stderr. It is not filed, because an "
            "exception message routinely carries a local path.",
            "",
        ]

    lines += ["---", "", f"Re-run: `uv run consistency-check audit --repo {repo_name}`."]
    return "\n".join(lines).rstrip() + "\n"


def render_child_issue(repo_name: str, finding: Finding) -> str | None:
    """Render a child issue body. Returns None for MAY failures (handled inline in the umbrella)."""
    if finding.status != FindingStatus.FAIL:
        return None
    if finding.tier == Tier.MAY:
        return None
    return (
        f"# {finding.rule_id} — {finding.tier.value} failure in `{repo_name}`\n"
        f"\n"
        f"**Evidence.** {_evidence(finding)}\n"
        f"\n"
        f"**Standards reference.** See `consistency-check/docs/standards/` "
        f"for rule {finding.rule_id}.\n"
        f"\n"
        f"**Re-run after fix.**\n"
        f"\n"
        f"```\nuv run consistency-check audit --repo {repo_name}\n```\n"
    )


def child_issue_title(repo_name: str, rule_id: str) -> str:
    """Canonical title for a child issue. Used for idempotency by the filer."""
    return f"[consistency] {repo_name}: {rule_id}"


def umbrella_issue_title(repo_name: str) -> str:
    """Canonical title for a per-repo umbrella issue."""
    return f"[consistency] {repo_name}: audit umbrella"


def _stage_section(findings: list[Finding], declared: Stage | None) -> list[str]:
    out = ["## Stage", ""]
    if declared is None:
        out += [
            "Unstaged — add an `S0`-`S4` token to the README `## Status` section.",
            "",
        ]
        return out
    at_or_below = [f for f in findings if stage_rank(f.min_stage) <= stage_rank(declared)]
    gate_fails = [f for f in at_or_below if f.tier == Tier.MUST and f.status == FindingStatus.FAIL]
    if gate_fails:
        ids = ", ".join(f.rule_id for f in gate_fails)
        out.append(f"Declared **{declared.value}**; {declared.value} gates failing: {ids}.")
    else:
        out.append(f"Declared **{declared.value}**; compliant through {declared.value} gates.")
    nxt = next_stage(declared)
    if nxt is not None:
        pending = sorted(
            {
                f.rule_id
                for f in findings
                if f.min_stage is nxt
                and f.applicable
                and f.status in (FindingStatus.FAIL, FindingStatus.NA)
            }
        )
        if pending:
            out += ["", f"To reach **{nxt.value}**: {', '.join(pending)}."]
    out.append("")
    return out


def _summary_table(findings: list[Finding]) -> str:
    counts: dict[Tier, dict[FindingStatus, int]] = {
        t: dict.fromkeys(FindingStatus, 0) for t in Tier
    }
    for f in findings:
        counts[f.tier][f.status] += 1
    rows = ["| Tier | pass | fail | n/a | error |", "| --- | --- | --- | --- | --- |"]
    rows.extend(
        f"| {t.value} | {counts[t][FindingStatus.PASS]} | {counts[t][FindingStatus.FAIL]} | "
        f"{counts[t][FindingStatus.NA]} | {counts[t][FindingStatus.ERROR]} |"
        for t in _TIER_ORDER
    )
    return "\n".join(rows)
