"""Markdown report emitter."""

from __future__ import annotations

from consistency_check.stage import next_stage, stage_rank
from consistency_check.types import Finding, FindingStatus, Stage, Tier

_TIER_ORDER = (Tier.MUST, Tier.SHOULD, Tier.MAY)


def render_umbrella(
    repo_name: str, findings: list[Finding], *, declared_stage: Stage | None = None
) -> str:
    """Render a per-repo umbrella issue body summarizing all findings."""
    summary = _summary_table(findings)
    failures = [f for f in findings if f.status == FindingStatus.FAIL]
    must_fails = [f for f in failures if f.tier == Tier.MUST]
    should_fails = [f for f in failures if f.tier == Tier.SHOULD]
    may_fails = [f for f in failures if f.tier == Tier.MAY]
    errors = [f for f in findings if f.status == FindingStatus.ERROR]

    lines: list[str] = [
        f"# Consistency audit: `{repo_name}`",
        "",
        "Generated by `consistency-check`. "
        "Authoritative standards: `consistency-check/docs/standards/`.",
        "",
        "## Summary",
        "",
        summary,
        "",
    ]

    lines += _stage_section(findings, declared_stage)

    if must_fails or should_fails:
        lines += ["## Required fixes (MUST / SHOULD)", ""]
        if must_fails:
            lines += [f"### MUST ({len(must_fails)})", ""]
            lines.extend(f"- **{f.rule_id}** — {f.evidence} → see child issue." for f in must_fails)
            lines.append("")
        if should_fails:
            lines += [f"### SHOULD ({len(should_fails)})", ""]
            lines.extend(
                f"- **{f.rule_id}** — {f.evidence} → see child issue." for f in should_fails
            )
            lines.append("")

    if may_fails:
        lines += [f"## Suggestions (MAY) — {len(may_fails)}", ""]
        lines.extend(f"- **{f.rule_id}** — {f.evidence}" for f in may_fails)
        lines.append("")

    if errors:
        lines += [f"## Audit errors ({len(errors)})", ""]
        for f in errors:
            first_line = f.evidence.splitlines()[0] if f.evidence else "unknown"
            lines.append(f"- **{f.rule_id}** — {first_line}")
        lines.append("")

    lines += ["---", "", f"Re-run: `uv run consistency-check audit --repo {repo_name}`."]
    return "\n".join(lines).rstrip() + "\n"


def render_child_issue(repo_name: str, finding: Finding) -> str | None:
    """Render a child issue body. Returns None for MAY failures (handled inline in the umbrella)."""
    if finding.status != FindingStatus.FAIL:
        return None
    if finding.tier == Tier.MAY:
        return None
    return (
        f"# {finding.rule_id} — {finding.tier.value} failure in `{repo_name}`\n"
        f"\n"
        f"**Evidence.** {finding.evidence}\n"
        f"\n"
        f"**Standards reference.** See `consistency-check/docs/standards/` "
        f"for rule {finding.rule_id}.\n"
        f"\n"
        f"**Re-run after fix.**\n"
        f"\n"
        f"```\nuv run consistency-check audit --repo {repo_name}\n```\n"
    )


def child_issue_title(repo_name: str, rule_id: str) -> str:
    """Canonical title for a child issue. Used for idempotency by the filer."""
    return f"[consistency] {repo_name}: {rule_id}"


def umbrella_issue_title(repo_name: str) -> str:
    """Canonical title for a per-repo umbrella issue."""
    return f"[consistency] {repo_name}: audit umbrella"


def _stage_section(findings: list[Finding], declared: Stage | None) -> list[str]:
    out = ["## Stage", ""]
    if declared is None:
        out += [
            "Unstaged — add an `S0`-`S4` token to the README `## Status` section.",
            "",
        ]
        return out
    at_or_below = [f for f in findings if stage_rank(f.min_stage) <= stage_rank(declared)]
    gate_fails = [f for f in at_or_below if f.tier == Tier.MUST and f.status == FindingStatus.FAIL]
    if gate_fails:
        ids = ", ".join(f.rule_id for f in gate_fails)
        out.append(f"Declared **{declared.value}**; {declared.value} gates failing: {ids}.")
    else:
        out.append(f"Declared **{declared.value}**; compliant through {declared.value} gates.")
    nxt = next_stage(declared)
    if nxt is not None:
        pending = sorted(
            {
                f.rule_id
                for f in findings
                if f.min_stage is nxt and f.status in (FindingStatus.FAIL, FindingStatus.NA)
            }
        )
        if pending:
            out += ["", f"To reach **{nxt.value}**: {', '.join(pending)}."]
    out.append("")
    return out


def _summary_table(findings: list[Finding]) -> str:
    counts: dict[Tier, dict[FindingStatus, int]] = {
        t: dict.fromkeys(FindingStatus, 0) for t in Tier
    }
    for f in findings:
        counts[f.tier][f.status] += 1
    rows = ["| Tier | pass | fail | n/a | error |", "| --- | --- | --- | --- | --- |"]
    rows.extend(
        f"| {t.value} | {counts[t][FindingStatus.PASS]} | {counts[t][FindingStatus.FAIL]} | "
        f"{counts[t][FindingStatus.NA]} | {counts[t][FindingStatus.ERROR]} |"
        for t in _TIER_ORDER
    )
    return "\n".join(rows)
